version: '3'
services:
  currency-converter.app.run_all:
    container_name: currency-converter.app.run_all
    image: "currency-converter.app:latest"
    ports:
      - 8090:8080
    environment:
      - "spring.profiles.active=docker"
      - "DB_JDBC_URL=jdbc:postgresql://currency-converter.postgres.run_all:5432/postgres"
      - "DB_USERNAME=postgres"
      - "DB_PASSWORD=postgres"
  currency-converter-ui.app.run_all:
    container_name: currency-converter-ui.app.run_all
    image: "currency-converter-ui.app:latest"
    ports:
      - 3000:80
    environment:
        - "API_HOST=http://localhost:8090"
  currency-converter.postgres.run_all:
    container_name: currency-converter.postgres.run_all
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
