version: '3'
services:
  fee-editor.postgres:
    container_name: fee-editor.postgres
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
