version: '3'
services:
  currency-converter.postgres:
    container_name: currency-converter.postgres
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
