###
PUT http://localhost:8080/fee-editor/exchangeFees HTTP/1.1
Content-Type: application/json

{ "exchangeFee" : { "from" : "RUB", "to": "EUR", "fee":  0.05} }

<> 2020-12-09T075049.200.json

###
DELETE http://localhost:8080/fee-editor/exchnageFees?from=RUB&to=EUR

###
GET http://localhost:8080/fee-editor/currencies

###
GET http://localhost:8080/fee-editor/conversion?from=RUB&to=EUR&amount=100